### ISSUE TITLE
Issues when launching the bot

### ISSUE THREAD

**Issue by Kraker01** [OscarGTH/Maplestory-Dojo-Bot#1] opened 2022-04-01 06:58 UTC
Hi, i'm on Windows 10 64bit, latest python 3.9.6, installed all the requirements.

If i launch "python dojobot.py", nothing happens.
If i launch "python dojobot_gui.py", i receive this error: 
 File "C:\Users\Marco\Downloads\Maplestory-Dojo-Bot-main\src\dojobot_gui.py", line 721
    match child.winfo_name():
          ^
SyntaxError: invalid syntax

Which Maple Story version should i use? Nexon launcher or Steam?

**Comment by OscarGTH** [comment] 2022-04-01 07:33
Greetings,


I'll look into this issue today. Thank you for bringing it into my
attention :) I'll get back to you asap.

I will also write a bit better documentation for this. I didn't know anyone
would actually use this hahah.

Best regards,
Oscar

pe 1. huhtik. 2022 klo 8.58 Kraker01 ***@***.***> kirjoitti:

**Comment by OscarGTH** [comment] 2022-04-01 07:37
Alright, it seems that the issue is with your Python version. "Match case" feature was introduced in Python 3.10.0 and your version is 3.9.6.
Please upgrade your Python version and run "dojobot_gui.py" to start the bot. If you are running the uncompiled version of the bot, you should be running your IDE as an administrator.

**Comment by Kraker01** [comment] 2022-04-01 08:22
Updated Python, uninstalling completely 3.9.6 and installing from scratch every dependencies. I'm experiencing a new error:

Traceback (most recent call last):
  File "C:\Users\Marco\Downloads\Maplestory-Dojo-Bot-main\src\dojobot_gui.py", line 1003, in <module>
    app = MainApplication(root)
  File "C:\Users\Marco\Downloads\Maplestory-Dojo-Bot-main\src\dojobot_gui.py", line 39, in __init__
    self.create_styles()
  File "C:\Users\Marco\Downloads\Maplestory-Dojo-Bot-main\src\dojobot_gui.py", line 56, in create_styles
    self.parent.configure(cursor = "@MapleCursor.ani")
  File "C:\Users\Marco\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1675, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Users\Marco\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1665, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: bad cursor spec "@MapleCursor.ani"

I'm not using any IDE (I'm not a programmer), i'm using Windows CMD (as Admin) and command line python

**Comment by OscarGTH** [comment] 2022-04-01 08:29
Alright, using CMD is just fine as long as it has admin rights.

Your new issue stems from running the program from the src directory instead of the root directory.
To fix your issue:
- Navigate to folder Maplestory-Dojo-Bot/
- Run command "python src/dojobot_gui.py"
- Program should open.


Issue happened because the program was looking for the cursor file from the running directory, which in your case seemed to be the "src" folder instead of the root folder "bot". This lead to the program not finding the cursor file and crashing. I will make a better fix for this later.

**Comment by OscarGTH** [comment] 2022-04-01 08:30
I can upload the compiled version for you later today which includes the EXE-file and all the necessary dependencies and packages.

**Comment by OscarGTH** [comment] 2022-04-01 09:23
Please, fetch the newest changeset of this repository and run "pip install -r requirements.txt" again. I updated the dependencies so you might get some errors with the older dependencies.

**Comment by Kraker01** [comment] 2022-04-01 12:38
Started. Things i've done: 
- downloaded new files from your repo
- installed all the new requirements
- moved 3 files from /src into bot main folder
- launched the bot using "python dojobot_gui.py"

I'm going to test it asap

**Comment by OscarGTH** [comment] 2022-04-01 13:07
You don't need to move any files to different folders :P You can leave them be in the "src" folder and I highly recommend leaving them there actually. Maybe it'd be easier if  you would compile the program into an executable. You can find instructions for that in the repository main ReadMe-file :) Good luck! Let me know if you need extra assistance with anything related to this.

**Closed as completed** 2022-04-04 10:18 UTC
